"""Bitbucket Cloud REST + git push helpers."""

from __future__ import annotations

import re
import subprocess
from typing import TYPE_CHECKING

import requests
from loguru import logger

from config import Settings
from models.issue_models import ClaudeExecutionResult, JiraIssue, PullRequestResult, ValidationResult

if TYPE_CHECKING:
    pass


def _auth(settings: Settings) -> tuple[str, str]:
    return settings.atlassian_email, settings.atlassian_api_token


def _bitbucket_http_kwargs(settings: Settings) -> dict:
    """Repository/workspace access tokens use Bearer; account uses Basic (email + API token)."""
    tok = (settings.bitbucket_git_access_token or "").strip()
    if tok:
        return {"headers": {"Authorization": f"Bearer {tok}"}}
    u, p = _auth(settings)
    return {"auth": (u, p)}


def _slugify(text: str, max_len: int = 40) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return (s[:max_len] or "fix").rstrip("-")


# Windows defaults subprocess text to cp1252; git/hooks may emit UTF-8 → UnicodeDecodeError in reader threads.
_GIT_RUN_TXT = {
    "capture_output": True,
    "text": True,
    "encoding": "utf-8",
    "errors": "replace",
}


def create_branch(local_repo: str, branch_name: str) -> None:
    subprocess.run(
        ["git", "-C", local_repo, "checkout", "-b", branch_name],
        check=True,
        **_GIT_RUN_TXT,
    )


def push_branch(settings: Settings, local_repo: str, branch_name: str) -> None:
    if settings.dry_run:
        logger.warning("DRY_RUN: skipping git push for {}", branch_name)
        return
    subprocess.run(
        ["git", "-C", local_repo, "push", "-u", "origin", branch_name],
        check=True,
        **_GIT_RUN_TXT,
    )


def create_pull_request(
    settings: Settings,
    issue: JiraIssue,
    branch_name: str,
    claude_result: ClaudeExecutionResult,
    validation: ValidationResult,
) -> PullRequestResult:
    ws = settings.bitbucket_workspace
    slug = settings.bitbucket_repo_slug
    url = f"{settings.bitbucket_rest_base}/repositories/{ws}/{slug}/pullrequests"
    title = f"[AI FIX] {issue.key} {issue.summary}"[:250]
    body = (
        "Automated conservative fix generated by the AI agent.\n\n"
        f"Issue: {issue.key}\n"
        f"Files changed: {claude_result.files_changed}\n"
        f"Lines changed: {claude_result.lines_changed}\n"
        f"Tests: {'PASS' if validation.tests_passed else 'FAIL'}\n"
        f"Lint: {'PASS' if validation.lint_passed else 'FAIL'}\n"
        f"Build: {'PASS' if validation.build_passed else 'FAIL'}\n"
        f"Confidence: {claude_result.confidence}\n\n"
        "Human review required before merge."
    )
    payload = {
        "title": title,
        "description": body,
        "source": {"branch": {"name": branch_name}},
        "destination": {"branch": {"name": settings.pr_target_branch}},
    }
    if settings.dry_run:
        logger.warning("DRY_RUN: would create PR {}", title)
        return PullRequestResult(
            pr_url="dry-run-no-pr",
            branch_name=branch_name,
            commit_hash="",
        )
    resp = requests.post(url, json=payload, timeout=120, **_bitbucket_http_kwargs(settings))
    if not resp.ok:
        logger.error("Bitbucket PR error {}: {}", resp.status_code, resp.text)
    resp.raise_for_status()
    data = resp.json()
    pr_url = data.get("links", {}).get("html", {}).get("href") or ""
    return PullRequestResult(
        pr_url=pr_url,
        branch_name=branch_name,
        commit_hash="",
    )


def commit_all(local_repo: str, message: str) -> str:
    subprocess.run(
        ["git", "-C", local_repo, "add", "-A"],
        check=True,
        **_GIT_RUN_TXT,
    )
    cmt = subprocess.run(
        ["git", "-C", local_repo, "commit", "-m", message],
        check=False,
        **_GIT_RUN_TXT,
    )
    if cmt.returncode != 0:
        err = ((cmt.stderr or "") + "\n" + (cmt.stdout or "")).strip()[:8000]
        logger.error("git commit failed (exit {}): {}", cmt.returncode, err or "(no output)")
        raise subprocess.CalledProcessError(
            cmt.returncode,
            ["git", "-C", local_repo, "commit", "-m", message],
            output=cmt.stdout,
            stderr=cmt.stderr,
        )
    cp = subprocess.run(
        ["git", "-C", local_repo, "rev-parse", "HEAD"],
        check=True,
        **_GIT_RUN_TXT,
    )
    return cp.stdout.strip()


def publish_pr(
    settings: Settings,
    issue: JiraIssue,
    local_repo: str,
    branch_name: str,
    claude_result: ClaudeExecutionResult,
    validation: ValidationResult,
) -> PullRequestResult:
    if settings.dry_run:
        logger.warning("DRY_RUN: skipping branch/commit/push/PR for {}", issue.key)
        return PullRequestResult(
            pr_url="dry-run",
            branch_name=branch_name,
            commit_hash="",
        )

    logger.info("git checkout -b {}", branch_name)
    create_branch(local_repo, branch_name)
    msg = f"[AI FIX] {issue.key} conservative automated bug fix"
    logger.info("git add / commit...")
    commit_hash = commit_all(local_repo, msg)
    logger.info("git push -u origin {} ...", branch_name)
    push_branch(settings, local_repo, branch_name)
    logger.info("Bitbucket: creating pull request via REST...")
    pr = create_pull_request(settings, issue, branch_name, claude_result, validation)
    return PullRequestResult(
        pr_url=pr.pr_url,
        branch_name=branch_name,
        commit_hash=commit_hash,
    )


def branch_name_for_issue(issue: JiraIssue) -> str:
    tail = _slugify(issue.summary)
    return f"aifix/{issue.key.lower()}-{tail}"
